import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { palette, PostCard, ScreenHeader } from '@/components/zoo-ui';
import { useZoo } from '@/data/zoo-context';

const animalTags = ['犬', '猫', '鳥', '爬虫類', 'パンダ', 'キリン', 'タヌキ', 'シカ', 'ライオン', 'クマ', 'ゾウ', 'サル', 'ウサギ', 'ウマ', 'ウシ', 'ブタ', 'ヒツジ', 'ヤギ', 'キツネ', 'リス', '伝説上の生物', 'タコ', 'イカ', 'その他'];

export default function DiscoverScreen() {
  const { posts, toggleLike, isLoading, isRefreshing, isLoadingMore, hasMore, syncError, refreshPosts, loadMorePosts } = useZoo();
  const router = useRouter();
  const [query, setQuery] = useState('');
  const [selectedTag, setSelectedTag] = useState<string | null>(null);
  const visiblePosts = useMemo(() => { const keyword = query.trim().toLocaleLowerCase('ja'); return posts.filter(post => { const matchesTag = !selectedTag || post.animal.includes(selectedTag); const target = `${post.animal} ${post.location} ${post.description}`.toLocaleLowerCase('ja'); return matchesTag && (!keyword || target.includes(keyword)); }); }, [posts, query, selectedTag]);
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={isRefreshing} onRefresh={refreshPosts} tintColor={palette.green} colors={[palette.green]} />}>
    <ScreenHeader eyebrow="MACHINAKA ZOO" title="みつける" right={<View style={styles.bell}><Text style={{ fontSize: 18 }}>♢</Text></View>} />
    {isLoading && <View style={styles.syncing}><ActivityIndicator size="small" color={palette.green} /><Text style={styles.syncingText}>最新の投稿を読み込み中…</Text></View>}
    {syncError && <View style={styles.errorBanner}><Text style={styles.errorText}>{syncError}</Text><Pressable onPress={refreshPosts} style={styles.retry}><Text style={styles.retryText}>再試行</Text></Pressable></View>}
    <View style={styles.searchWrap}><Text style={styles.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="動物名・場所・説明から検索" placeholderTextColor="#929A95" returnKeyType="search" style={styles.searchInput} />{query.length > 0 && <Pressable onPress={() => setQuery('')} style={styles.clear}><Text style={styles.clearText}>×</Text></Pressable>}</View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tags}><Pressable onPress={() => setSelectedTag(null)} style={[styles.tag, selectedTag === null && styles.tagActive]}><Text style={[styles.tagText, selectedTag === null && styles.tagTextActive]}>すべて</Text></Pressable>{animalTags.map(tag => <Pressable key={tag} onPress={() => setSelectedTag(current => current === tag ? null : tag)} style={[styles.tag, selectedTag === tag && styles.tagActive]}><Text style={[styles.tagText, selectedTag === tag && styles.tagTextActive]}>{tag}</Text></Pressable>)}</ScrollView>
    {visiblePosts.length > 0 ? <View style={styles.grid}>{visiblePosts.map(post => <View key={post.id} style={styles.gridItem}><PostCard compact hideAnimalTag post={post} onLike={() => toggleLike(post.id)} onOpen={() => router.push({ pathname: '/post-detail/[id]', params: { id: post.id } })} /></View>)}</View> : <View style={styles.empty}><Text style={styles.emptyIcon}>⌕</Text><Text style={styles.emptyTitle}>該当する投稿がありません</Text><Text style={styles.emptyText}>検索語や動物タグを変えてみてください</Text><Pressable onPress={() => { setQuery(''); setSelectedTag(null); }} style={styles.reset}><Text style={styles.resetText}>条件をリセット</Text></Pressable></View>}
    {hasMore && !query && !selectedTag && <Pressable disabled={isLoadingMore} onPress={loadMorePosts} style={[styles.loadMore, isLoadingMore && { opacity: .6 }]}>{isLoadingMore ? <ActivityIndicator size="small" color={palette.green} /> : <Text style={styles.loadMoreText}>さらに読み込む</Text>}</Pressable>}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: palette.cream }, content: { paddingHorizontal: 18, paddingBottom: 120, maxWidth: 640, width: '100%', alignSelf: 'center' }, bell: { width: 42, height: 42, borderRadius: 21, backgroundColor: palette.card, borderWidth: 1, borderColor: palette.line, alignItems: 'center', justifyContent: 'center' }, syncing: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: -12, marginBottom: 12 }, syncingText: { color: palette.muted, fontSize: 12 }, errorBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FCEBE7', borderRadius: 12, padding: 11, marginTop: -10, marginBottom: 12 }, errorText: { flex: 1, color: '#8B4138', fontSize: 12, fontWeight: '700' }, retry: { backgroundColor: '#FFF8F5', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 7 }, retryText: { color: '#8B4138', fontSize: 11, fontWeight: '900' }, searchWrap: { minHeight: 46, flexDirection: 'row', alignItems: 'center', backgroundColor: palette.card, borderWidth: 1, borderColor: palette.line, borderRadius: 15, paddingHorizontal: 13 }, searchIcon: { color: palette.green, fontSize: 20, marginRight: 8 }, searchInput: { flex: 1, color: palette.ink, fontSize: 14, paddingVertical: 12 }, clear: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' }, clearText: { color: palette.muted, fontSize: 22 }, tags: { gap: 8, paddingVertical: 14, paddingRight: 8 }, tag: { borderWidth: 1, borderColor: palette.line, backgroundColor: palette.card, borderRadius: 18, paddingHorizontal: 16, paddingVertical: 8 }, tagActive: { borderColor: palette.green, backgroundColor: palette.green }, tagText: { color: palette.muted, fontSize: 12, fontWeight: '700' }, tagTextActive: { color: '#fff', fontWeight: '900' }, grid: { flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -6, rowGap: 12 }, gridItem: { width: '50%', paddingHorizontal: 6 }, loadMore: { alignSelf: 'center', minWidth: 150, minHeight: 44, marginTop: 22, borderRadius: 22, backgroundColor: palette.sage, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 22 }, loadMoreText: { color: palette.deep, fontSize: 13, fontWeight: '900' }, empty: { marginTop: 30, padding: 30, alignItems: 'center', backgroundColor: palette.card, borderWidth: 1, borderColor: palette.line, borderRadius: 20 }, emptyIcon: { color: palette.green, fontSize: 36 }, emptyTitle: { color: palette.ink, fontSize: 16, fontWeight: '900', marginTop: 10 }, emptyText: { color: palette.muted, fontSize: 12, marginTop: 6, textAlign: 'center' }, reset: { marginTop: 18, backgroundColor: palette.sage, borderRadius: 18, paddingVertical: 9, paddingHorizontal: 17 }, resetText: { color: palette.deep, fontSize: 12, fontWeight: '900' } });
